name: game_services_firebase_auth_example
description: Demonstrates how to use the game_services_firebase_auth plugin.

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  game_services_firebase_auth:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
